// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY0Tgornfcz0vOwbDSIaykDFwrL-Qpz8Q',
    appId: '1:259524359486:web:eaa9f1ca32e7cc880c286f',
    messagingSenderId: '259524359486',
    projectId: 'message-9dd39',
    authDomain: 'message-9dd39.firebaseapp.com',
    storageBucket: 'message-9dd39.firebasestorage.app',
    measurementId: 'G-WCM0ZC3308',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7lH39lnI2FOdoec1yNty8rEYxnwPy27g',
    appId: '1:259524359486:android:027da66e61cd419d0c286f',
    messagingSenderId: '259524359486',
    projectId: 'message-9dd39',
    storageBucket: 'message-9dd39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqVy7NTui0q71DYJPz3uP4McwjQmpFD8A',
    appId: '1:259524359486:ios:334ac0e8d140a7050c286f',
    messagingSenderId: '259524359486',
    projectId: 'message-9dd39',
    storageBucket: 'message-9dd39.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqVy7NTui0q71DYJPz3uP4McwjQmpFD8A',
    appId: '1:259524359486:ios:334ac0e8d140a7050c286f',
    messagingSenderId: '259524359486',
    projectId: 'message-9dd39',
    storageBucket: 'message-9dd39.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY0Tgornfcz0vOwbDSIaykDFwrL-Qpz8Q',
    appId: '1:259524359486:web:d162bf7566e0186e0c286f',
    messagingSenderId: '259524359486',
    projectId: 'message-9dd39',
    authDomain: 'message-9dd39.firebaseapp.com',
    storageBucket: 'message-9dd39.firebasestorage.app',
    measurementId: 'G-ZWV4DNELQ9',
  );

}